### ISSUE TITLE
Dual image mode

### ISSUE THREAD

**Issue by vincepota-zz** [fred3m/astromatic_wrapper#2]
Can you confirm that the "dual image mode" is not implemented in the current version of astromatic_wrapper? I could not find any hint in the documentation

**Comment by fred3m** [comment]
That's correct, dual image mode is not implemented at this time. I would also recommend using the astropyp package instead of astromatic_wrapper. I am no longer working on astromatic_wrapper but an improved API has been implemented in astropyp.wrappers.astromatic, along with better support for pipelines and ldac files. The only drawback is that I have yet to write the documentation for astropyp, although there is a directory with ipython notebook examples that you might find useful.
